Updated gmux script

diff --git a/scripts/.local/bin/gmux b/scripts/.local/bin/gmux
--- a/scripts/.local/bin/gmux
+++ b/scripts/.local/bin/gmux
@@ -1,22 +1,56 @@
 #!/bin/bash
-# Simple script for setting up a tmux session with a few windows and panes.
-# Just how I like it.
+# Simple script for setting up tmux sessions. Based on templates.
+# Author: @lnus
+#
+# Usage: gmux <session-name> <session-type>
+#
+# Example: gmux my-session bare (will create a new session called my-session with a bare tmux setup)
+# Example: gmux my-session nvim (will create a new session called my-session with a NeoVim setup)
+#
+# TODO: Add more types
+# TODO: Add a way to add custom templates
+# TODO: Rewrite this in Python or something if it gets too big
 
-# Start a new tmux session
-tmux new-session -s "$1" -n "main" -d
+# Check if the session name is provided
+if [ -z "$1" ] || [ -z "$2" ]; then
+    echo "Usage: gmux <session-name> <session-type>"
+    echo "Available types: bare, nvim, mega"
+    exit 1
+fi
 
-# Create a new window
-tmux new-window -n "vim" -t "$1"
+# Check if the session already exists
+if tmux has-session -t "$1" 2>/dev/null; then
+    echo "Session already exists"
+    exit 1
+fi
 
-# Spawn NeoVim in the new window and split the pane
-tmux send-keys -t "$1:1" "nvim $(pwd)" C-m
-tmux split-window -h -t "$1:1"
+# Bare: Create a new session and attach to it
+if [ "$2" == "bare" ]; then
+    tmux new-session -s "$1" -n "main" -d
+    tmux attach-session -t "$1:0"
+    exit 0
+fi
 
-# Create a new window
-tmux new-window -n "git" -t "$1"
+# Nvim: Create a new session, a new window, spawn NeoVim in the new window and split the pane
+if [ "$2" == "nvim" ]; then
+    tmux new-session -s "$1" -n "main" -d
+    tmux send-keys -t "$1:0" "nvim $(pwd)" C-m
+    tmux split-window -h -t "$1:0"
+    tmux attach-session -t "$1:0"
+    exit 0
+fi
 
-# Spawn git status in the new window
-tmux send-keys -t "$1:2" "git status" C-m
+# Mega: Create a new session, and three split panes
+if [ "$2" == "mega" ]; then
+    tmux new-session -s "$1" -n "main" -d
+    # tmux send-keys -t "$1:0" "nvim $(pwd)" C-m
+    tmux split-window -h -t "$1:0"
+    tmux split-window -v -t "$1:0.1"
+    tmux attach-session -t "$1:0.0"
+    exit 0
+fi
 
-# Finally, attach to the session, in the main window
-tmux attach-session -t "$1:0"
+# If the session type is not caught by any of the above, exit with an error
+echo "Invalid session type"
+echo "Available types: bare, nvim, mega"
+exit 1
